export const browserCoreExamples = [
  "shehzadalgo browser status",
  "shehzadalgo browser start",
  "shehzadalgo browser stop",
  "shehzadalgo browser tabs",
  "shehzadalgo browser open https://example.com",
  "shehzadalgo browser focus abcd1234",
  "shehzadalgo browser close abcd1234",
  "shehzadalgo browser screenshot",
  "shehzadalgo browser screenshot --full-page",
  "shehzadalgo browser screenshot --ref 12",
  "shehzadalgo browser snapshot",
  "shehzadalgo browser snapshot --format aria --limit 200",
  "shehzadalgo browser snapshot --efficient",
  "shehzadalgo browser snapshot --labels",
];

export const browserActionExamples = [
  "shehzadalgo browser navigate https://example.com",
  "shehzadalgo browser resize 1280 720",
  "shehzadalgo browser click 12 --double",
  'shehzadalgo browser type 23 "hello" --submit',
  "shehzadalgo browser press Enter",
  "shehzadalgo browser hover 44",
  "shehzadalgo browser drag 10 11",
  "shehzadalgo browser select 9 OptionA OptionB",
  "shehzadalgo browser upload /tmp/shehzadalgo/uploads/file.pdf",
  'shehzadalgo browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "shehzadalgo browser dialog --accept",
  'shehzadalgo browser wait --text "Done"',
  "shehzadalgo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "shehzadalgo browser console --level error",
  "shehzadalgo browser pdf",
];
