name: ShehzadAlgo
options:
  bundleIdPrefix: ai.shehzadalgo
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  ShehzadAlgoKit:
    path: ../shared/ShehzadAlgoKit
  Swabble:
    path: ../../Swabble

schemes:
  ShehzadAlgo:
    shared: true
    build:
      targets:
        ShehzadAlgo: all
    test:
      targets:
        - ShehzadAlgoTests

targets:
  ShehzadAlgo:
    type: application
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: Sources
    dependencies:
      - target: ShehzadAlgoShareExtension
        embed: true
      - package: ShehzadAlgoKit
      - package: ShehzadAlgoKit
        product: ShehzadAlgoChatUI
      - package: ShehzadAlgoKit
        product: ShehzadAlgoProtocol
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(SHEHZADALGO_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(SHEHZADALGO_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(SHEHZADALGO_APP_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(SHEHZADALGO_APP_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: ShehzadAlgo
        CFBundleIconName: AppIcon
        CFBundleURLTypes:
          - CFBundleURLName: ai.shehzadalgo.ios
            CFBundleURLSchemes:
              - shehzadalgo
        CFBundleShortVersionString: "2026.2.17"
        CFBundleVersion: "20260217"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: ShehzadAlgo discovers and connects to your ShehzadAlgo gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _shehzadalgo-gw._tcp
        NSCameraUsageDescription: ShehzadAlgo can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: ShehzadAlgo uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: ShehzadAlgo can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: ShehzadAlgo needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: ShehzadAlgo uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  ShehzadAlgoShareExtension:
    type: app-extension
    platform: iOS
    configFiles:
      Debug: Signing.xcconfig
      Release: Signing.xcconfig
    sources:
      - path: ShareExtension
    dependencies:
      - package: ShehzadAlgoKit
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: "$(SHEHZADALGO_CODE_SIGN_STYLE)"
        DEVELOPMENT_TEAM: "$(SHEHZADALGO_DEVELOPMENT_TEAM)"
        PRODUCT_BUNDLE_IDENTIFIER: "$(SHEHZADALGO_SHARE_BUNDLE_ID)"
        PROVISIONING_PROFILE_SPECIFIER: "$(SHEHZADALGO_SHARE_PROFILE)"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
    info:
      path: ShareExtension/Info.plist

  ShehzadAlgoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ShehzadAlgo
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.shehzadalgo.ios.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ShehzadAlgo.app/ShehzadAlgo"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: ShehzadAlgoTests
        CFBundleShortVersionString: "2026.2.17"
        CFBundleVersion: "20260217"
